version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run start:dev
    restart: unless-stopped
